default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    - id: clang-format
      files: \.(cpp|h)$
      args: ["-i"]
  - repo: https://github.com/google/yapf/
    rev: v0.40.2
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: ["--style=.style.yapf", "-i"]
        types: [python]
